

ZMQ_XPUB_PORT: 5558

TG_API_KEY: "my-telegram-api-key" 

OWNER: 123456767
RECEIVERS: 
  - tg_user_id: 123456767
    username: "my_telegram_username"
    perms: "all"

MULTI_LINE: > 
   This
   is
   a multi line 
   ignore me 
   